### PR TITLE
bundle Python

### PR DESCRIPTION
**Pull request by guoci**
bundle Python with FragPipe
- reduce Python software installation issues
- make Python software issues easily reproducible, since users use the same bundled Python
- possibly add offline installs of Python packages in the future

### CODE REVIEW

**Review by fcyu — CHANGES_REQUESTED** [review]
It works! Thanks Guo Ci. 

The following are one question/issue and two suggestions.

1. It seems that the packages are installed to user's home folder. As we have discussed, they should be in the FragPipe folder to avoid messing up the user's local environment.
2. I suggest removing the Linux Python, just like we bundle the Win JRE but not the Linux JRE, since the Linux users/admins are supposed know how to config Python. 
3. Only bundle the Win Python in the FragPipe zip with the "jre" in the file name.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Ah, I know why my EasyPQP was installed to the user folder. I used the system's `pip`, not the FragPipe's `python -m`.

Thanks,

Fengchao

**Comment by guoci** [comment]
1. Make Python run in [isolated mode](https://docs.python.org/3/using/cmdline.html#cmdoption-I) for consistency
2. Bundle all the Python packages for offline use of FragPipe
image

**Comment by fcyu** [comment]
I got the following errors

```shell
SpecLibGen [Work dir: G:\ttt]
G:\Dropbox\code\FragPipe\MSFragger-GUI\build\github-release\FragPipe-23.0-build1\tools\python_Windows\python\python.exe -u -I G:\Dropbox\code\FragPipe\MSFragger-GUI\build\github-release\FragPipe-23.0-build1\tools\speclib\gen_con_spec_lib.py G:\dev\2021-03-23-decoys-reviewed-contam-UP000005640.fas G:\ttt unused G:\ttt True unused use_easypqp ciRT;noIM 11 "--unimod G:/Dropbox/code/FragPipe/MSFragger-GUI/build/github-release/FragPipe-23.0-build1/tools/unimod_old.xml --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.0" delete_intermediate_files G:\ttt\filelist_speclibgen.txt
Traceback (most recent call last):
  File "G:\Dropbox\code\FragPipe\MSFragger-GUI\build\github-release\FragPipe-23.0-build1\tools\speclib\gen_con_spec_lib.py", line 21, in <module>
    from common_funcs import (str_to_path, name_no_ext, os_fspath)
ModuleNotFoundError: No module named 'common_funcs'
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
```

Also, I have some additional suggestions
1. There are both `python` and `python.zip` in the `python_Linux` and `python_Windows` folders. Maybe don't need to bundle the zip files.
2. Currently, installing the Python packages takes a long time. Maybe need to improve the GUI to show some progress when installing. Right now, it just freeze or has no progress.

Thanks,

Fengchao

**Comment by fcyu** [comment]
@guoci the latest commit ce9989e0290bed27092d4eaaaa426498bb0df680 uses the Python in my system home folder: 

```shell
'C:\Users\yufe\AppData\Roaming\Python\Python311\Scripts\easypqp.exe' convert --unimod G:/Dropbox/code/FragPipe/MSFragger-GUI/build/github-release/FragPipe-23.0-build5/tools/unimod_old.xml --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types '['"'"'b'"'"','"'"'y'"'"',]' --enable_unannotated --pepxml '['"'"'G:\\ttt\\interact-b1926_293T_proteinID_06A_QE3_122212.pep.xml'"'"']' --spectra 'F:\data\PXD001468\b1926_293T_proteinID_06A_QE3_122212.mzML' --exclude-range -1.5,3.5 --psms b1926_293T_proteinID_06A_QE3_122212.psmpkl --peaks b1926_293T_proteinID_06A_QE3_122212.peakpkl
'C:\Users\yufe\AppData\Roaming\Python\Python311\Scripts\easypqp.exe' convert --unimod G:/Dropbox/code/FragPipe/MSFragger-GUI/build/github-release/FragPipe-23.0-build5/tools/unimod_old.xml --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types '['"'"'b'"'"','"'"'y'"'"',]' --enable_unannotated --pepxml '['"'"'G:\\ttt\\interact-b1929_293T_proteinID_09A_QE3_122212.pep.xml'"'"']' --spectra 'F:\data\PXD001468\b1929_293T_proteinID_09A_QE3_122212.mzML' --exclude-range -1.5,3.5 --psms b1929_293T_proteinID_09A_QE3_122212.psmpkl --peaks b1929_293T_proteinID_09A_QE3_122212.peakpkl
'C:\Users\yufe\AppData\Roaming\Python\Python311\Scripts\easypqp.exe' library --psmtsv 'G:\ttt\psm.tsv' --peptidetsv 'G:\ttt\peptide.tsv' --rt_reference 'G:\ttt\irt.tsv' --out easypqp_lib_openswath.tsv --rt_lowess_fraction 0.0 'G:\ttt\filelist_easypqp_library.txt'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
easypqp, version 0.1.50
Executing "C:\Users\yufe\AppData\Roaming\Python\Python311\Scripts\easypqp.exe convert --unimod G:/Dropbox/code/FragPipe/MSFragger-GUI/build/github-release/FragPipe-23.0-build5/tools/unimod_old.xml --max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types ['b','y',] --enable_unannotated --pepxml ['G:\\ttt\\interact-b1926_293T_proteinID_06A_QE3_122212.pep.xml'] --spectra F:\data\PXD001468\b1926_293T_proteinID_06A_QE3_122212.mzML --exclude-range -1.5,3.5 --psms b1926_293T_proteinID_06A_QE3_122212.psmpkl --peaks b1926_293T_proteinID_06A_QE3_122212.peakpkl"
2024-12-13 09:56:11 - Info: Converting ['G:\\ttt\\interact-b1926_293T_proteinID_06A_QE3_122212.pep.xml'].
2024-12-13 09:56:11 - Info: Parsing run b1926_293T_proteinID_06A_QE3_122212.
2024-12-13 09:56:11 - Info: Parsing pepXML: G:\ttt\interact-b1926_293T_proteinID_06A_QE3_122212.pep.xml
2024-12-13 09:56:13 - Info: 23869 PSMs parsed.
2024-12-13 09:56:13 - Info: Generate theoretical spectra.
2024-12-13 09:56:15 - Info: Processing spectra from file F:\data\PXD001468\b1926_293T_proteinID_06A_QE3_122212.mzML.
...
```

[log_2024-12-13_09-57-52.txt](https://github.com/user-attachments/files/18127965/log_2024-12-13_09-57-52.txt)

Thanks,

Fengchao

**Comment by fcyu** [comment]
@guoci It works now. I will merge this pull request.

There are two TODOs in https://github.com/Nesvilab/FragPipe/pull/1923#issuecomment-2540022744, which I will create two issues as a reminder.

Thanks,

Fengchao

**Pull request merged**
