### PR TITLE
possible fix for #1652

### PR DESCRIPTION
**Pull request by guoci**
possible fix for #1652

### CODE REVIEW

**Comment by fcyu** [comment]
Thanks @guoci , but it doesn't work

Animation

Best,

Fengchao

**Comment by guoci** [comment]
Pasting the path doesn't work, but using mouse navigation does. I will check if that can be fixed.

**Comment by fcyu** [comment]
That's correct. But this is what Matt wants: type or paste the path, and then select the files. 

Best,

Fengchao

**Comment by guoci** [comment]
This new commit should allow users to type or paste paths.

**Comment by fcyu** [comment]
Thanks @guoci , it cause some errors when clicking "this PC" and "Desktop".

Animation

Best,

Fengchao

**Comment by fcyu** [comment]
Thanks @guoci , but the new commit broke the file chooser in the other buttons.

As you can see in the following gif, it can't go into `.d` because of https://github.com/Nesvilab/FragPipe/pull/1653/files#diff-23d6af456b2afdf3296b61117f8c4824b8c497351f63e93db00e6d4cdf9b8058R114. And after double-clicking, it load `*.d` for the database file, which it should not because the extension doesn't follow the FASTA file rules.

I guess you need to override `isTraversable` only when the file chooser is for the LC-MS files.

Animation

Best,

Fengchao

**Review by fcyu — APPROVED** [review]

**Pull request merged**
