### PR TITLE
Add msbooster scores pepxml develop

### PR DESCRIPTION
**Pull request by yangkl96**
added spectralsim and RTscore into interact.pepxml file

### CODE REVIEW

**Comment by prvst** [comment]
Can you share here an example of a file containing the new attributes?

**Comment by yangkl96** [comment]
[interact-NanoPOTS_Autosampler_FACS_MCF10A_50_30min_C2_r2.pep.zip](https://github.com/Nesvilab/FragPipe/files/8516202/interact-NanoPOTS_Autosampler_FACS_MCF10A_50_30min_C2_r2.pep.zip)

**Comment by fcyu** [comment]
@yangkl96 Please move `spectralsim` and `rtscore` out of `peptideprophet_result`. You can put them after `expect` score. The tag name should be `search_score` not `parameter`.

Best,

Fengchao

**Comment by fcyu** [comment]
@yangkl96 Thanks. Are there any reason of using `double` but not `float`?

Best,

Fengchao

**Comment by yangkl96** [comment]
not in particular, I can change to float if better?

**Comment by fcyu** [comment]
I can change it for you. I will also make some other changes.

**Comment by fcyu** [comment]
@yangkl96 I pushed the changes. Can you rerun the program and send the new pep.xml file to Felipe?

Thanks,

Fengchao

**Comment by yangkl96** [comment]
[interact-NanoPOTS_Autosampler_FACS_MCF10A_50_30min_C2_r2.pep.zip](https://github.com/Nesvilab/FragPipe/files/8516867/interact-NanoPOTS_Autosampler_FACS_MCF10A_50_30min_C2_r2.pep.zip)

**Comment by prvst** [comment]
done

**Pull request closed without merging**
