### PR TITLE
Sarah gui updates

### PR DESCRIPTION
**Pull request by sarah-haynes**
Updating some wording, tooltips, etc.

The 'Configuration Help' on Config tab and 'See the tutorial' on Workflow tab links still point to old location, but I couldn't find where to change them.
image

image

### CODE REVIEW

**Comment by guoci** [comment]
@sarah-haynes what is the new location?

**Review by fcyu — APPROVED** [review]

**Comment by fcyu** [comment]
It should be in the master branch. Let me change it.

**Comment by fcyu** [comment]
Actually, changing the master branch right now is not a good idea. We can wait for the official release. After that, we will merge the update branch to the master branch. So, everything will be corrected.

**Comment by guoci** [comment]
@fcyu The properties are fetched from the `updates` branch, not the `master` branch. So I think we can update it now, so that current users will get the correct link.
https://github.com/Nesvilab/FragPipe/blob/master/MSFragger-GUI/src/com/dmtavt/fragpipe/params/ThisAppProps.java#L105-L107

**Comment by fcyu** [comment]
Yes, can update `updates` branch.

**Pull request merged**
